config/routes.rb
Rails.application.routes.draw do

  root "flights#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flights, only: [:index]

  resources :bookings, only: [:new, :create, :show]
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, class_name: "Flight", foreign_key: :from_airport_id
    has_many :arriving_flights, class_name: "Flight", foreign_key: :to_airport_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    has_many :passengers
    belongs_to :flight

    accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_many :bookings
  has_many :passengers, through: :bookings

  belongs_to :from_airport, class_name: "Airport", foreign_key: :from_airport_id
  belongs_to :to_airport, class_name: "Airport", foreign_key: :to_airport_id

  scope :check_date, ->(date) {where("DATE(datetime) = ?", date)}

  def date_dmy
    self.datetime.strftime("%d/%m/%Y")
  end

  def date_ymd
    self.datetime.strftime("%Y-%m-%d")
  end

  def time
    self.datetime.strftime("%H:%M")
  end

end

app/models/passenger.rb
class Passenger < ApplicationRecord
    belongs_to :booking

    validates :name, presence: true
    validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def new
        @booking = Booking.new
        @flight = Flight.find(params[:flight_id])
    
        count = params[:num_tickets].to_i
        count.times { @booking.passengers.build }
    end

    def create
        @booking = Booking.new(booking_params)
        if @booking.save
            PassengerMailer.send_confirmed_booking(@booking)
            redirect_to @booking
        else
            @flight = Flight.find(params["booking"]["flight_id"])
            render :new
        end  
    end

    def show
        @booking = Booking.find(params[:id])
    end

    private

    def booking_params
        params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email])
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
    def index

        @from_airport = Flight.all.map{|u| [u.from_airport.code, u.from_airport_id]}.uniq
        @to_airport = Flight.all.map{|u| [u.to_airport.code, u.to_airport_id]}.uniq
        @date = Flight.all.order("datetime ASC").map{|u| [u.date_dmy, u.date_ymd]}.uniq
        @num_tickets = [[1,1],[2,2],[3,3],[4,4]]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/_booking_form.html.erb
<%= form_with model:@booking do |form|%>
    
    <br><br>
    
    <%= form.fields_for :passengers do |p_form| %>
        <div class="field">
            <%=p_form.label :Name%>
            <div class="control">
                <%=p_form.text_field :name%>
            </div>
        </div>

        <div class="field">
            <%=p_form.label :Email%>
            <div class="control">
                <%=p_form.text_field :email%>
            </div>
        </div>
    <%end%>

    <br>

    <%=form.hidden_field :flight_id, value: flight.id %>

    <div class="field is-grouped">
        <div class="control">
            <%=form.submit%>
        </div>
    </div>
<%end%>

app/views/bookings/new.html.erb
<h1>Passenger Form</h1>

<h2>Flight ID</h2>
<%=@flight.id%>

<h3>Departing from</h3>
<%=@flight.from_airport.code%>

<h3>Arriving at</h3>
<%=@flight.to_airport.code%>

<h3>Date</h3>
<%=@flight.date_dmy%>

<h3>Departure Time</h3>
<%=@flight.time%>

<h3>Duration</h3>
<%="#{@flight.duration} minutes"%>

<%= render "booking_form", flight: @flight%>

app/views/bookings/show.html.erb
<h1><b>Booking Information</b></h1>

<br>

<h2><i>Flight Information</i></h2>

<p>Flight ID</p>
<%=@booking.flight.id%>

<p>Departing from</p>
<%=@booking.flight.from_airport.code%>

<p>Arriving at</p>
<%=@booking.flight.to_airport.code%>

<p>Date</p>
<%=@booking.flight.date_dmy%>

<p>Departure Time</p>
<%=@booking.flight.time%>

<p>Duration</p>
<%="#{@booking.flight.duration} minutes"%>

<br><br>

<h2><i>Passenger Info</i></h2>

<%@booking.passengers.each do |p|%>
    <ul>
        <p><%=p.name%><p>
        <p><%=p.email%></p>
        <br>
    </ul>
<%end%>

app/views/flights/_search_flights_form.html.erb
<%= form_with url: "/flights", method: :get do |form|%>

    <%= form.label :From%>
    <%= select(:get, :from_id, @from_airport)%><br>

    <%= form.label :To%>
    <%= select(:get, :to_id, @to_airport)%><br>

    <%= form.label :Date%>
    <%= select(:get, :date, @date)%><br>


    <%= form.label :Number_of_Tickets%>
    <%= select(:get, :num_tickets, @num_tickets)%>

    <br>
    <%=form.submit%>
<%end%>

app/views/flights/_search_flights_results.html.erb
<h1>Flights</h1>

<%= form_with url: new_booking_path, method: :get do |form|%>

    <%p = params[:get]%>

    <% unless p == nil%>
        <% all_flights = Flight.where(
            from_airport_id: p["from_id"],
            to_airport_id: p["to_id"]).check_date(p["date"])
        %>

        <div>
            <%=form.submit%>
            <% all_flights.each do |flight|%>
                <ul>
                    <%=flight.from_airport.code %>
                    <%=flight.to_airport.code%>
                    <%=flight.datetime%>
                    <%# <%=flight.id%>
                
                    <%=form.radio_button :flight_id, flight.id%>
                </ul> 
            <%end%>
            <%=form.hidden_field :num_tickets, value: p["num_tickets"]%>
        </div>
    <%end%>
<%end%>

app/views/flights/index.html.erb
<body>
    <section class="section">
        <%= render "search_flights_form"%>
    </section>

    <section class="section">
        <%= render "search_flights_results"%>
    </section>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="hero is-primary is-small">
      <div class="hero-body">
          <h1 class="title">Odin-Flight-Booker</h1>
      </div>
    </section>
    <%= yield %>

    <%# <footer class="footer">
      <div class="content">
        <p>This is the footer</p>
      </div>
    </footer> %>
  </body>
</html>